### ISSUE TITLE
Тестовое задание Уно-Софт

### ISSUE THREAD

**Issue by mary-grigoriiva** [trainymonked/vk-vue#1]
Добрый вечер, Дмитрий.
На исправления вашего тестового задания у вас будет 3 попытки.
Необходимо, чтобы друзья отображались все таки сразу, а не по кнопке для каждого.
Только со второго нажатия на кнопку "Построить" отображается список всех друзей и подсветка.

**Comment by trainymonked** [comment]
> Только со второго нажатия на кнопку "Построить" отображается список всех друзей и подсветка.
Подскажите, пожалуйста, при каких условиях это происходит?
